[package]
name = "shimeji"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "*"

glfw = "*"
glutin = "*"
gl = "*"

image = "*"

# beryllium = "*"
# gl_generator = "*"
# glium = "*"
# tokio = "*"